In [1]:
import pandas as pd

In [3]:
drive.mount('/content/drive/')

Mounted at /content/drive/

In [4]:
df = pd.read_csv(
    '/content/drive/MyDrive/dados-programaria/licitacoes.csv',
    encoding='latin1',
    sep=';'
)

In [5]:
df.head(10)

,Número Licitação,Código UG,Nome UG,Código Modalidade Compra,Modalidade Compra,Número Processo,Objeto,Situação Licitação,Código Órgão Superior,Nome Órgão Superior,Código Órgão,Nome Órgão,UF,Município,Data Resultado Compra,Data Abertura,Valor Licitação
0,12016,160438,COMANDO 2 BRIGADA DE CAVALARIA MECANIZADA,-99,Pregão - Registro de Preço,80871182401201629,Objeto: Pregão Eletrônico - Aquisição de mater...,Evento de Resultado de Julgame,52000,Ministério da Defesa,52121,Comando do Exército,RS,URUGUAIANA,04/12/2018,17/08/2016,"18854,0000"
1,12017,160203,2º BATALHAO DE ENGENHARIA DE CONSTRUCAO,3,Concorrência,64040053530201713,Objeto: Contratação de empresa para construção...,Evento de Resultado de Julgame,52000,Ministério da Defesa,52121,Comando do Exército,PI,TERESINA,07/12/2018,NaN,"889571,4300"
2,12017,193002,DEPARTAMENTO NACIONAL DE OBRAS CONT.AS SECAS,2,Tomada de Preços,59400003079201636,Objeto: Contratação de empresa especializada n...,Evento de Resultado de Julgame,53000,Ministério da Integração e do Desenvolvime,22204,Departamento Nacional de Obras Contra as Seca,CE,FORTALEZA,07/12/2018,NaN,"865536,6500"
3,12018,925135,BANCO CENTRAL DO BRASIL - RECIFE,6,Dispensa de Licitação,148097,"Objeto: TV LED de 65 polegadas, UHD 4k, com co...",Encerrado,20101,Sem informação,25201,BANCO CENTRAL DO BRASIL-ORC.FISCAL/SEG.SOCIAL,-3,Inválido,04/12/2018,30/11/2018,"11075,9900"
4,12018,110101,GABINETE DA VICE-PRESIDENCIA DA REPUBLICA,7,Inexigibilidade de Licitação,00300000433201818,Objeto: Pretação de serviços de publicação de ...,Publicado,20000,Presidência da República,60000,Gabinete da Vice-Presidência da República,DF,BRASILIA,21/12/2018,NaN,"12000,0000"
5,12018,110102,SUPERINTENDENCIA REG. DE ADMIN. DA 2ª REGIAO,7,Inexigibilidade de Licitação,00592000507201888,Objeto: Licença de uso irrestrito da cópia do ...,Revogação,63000,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com vín,RJ,RIO DE JANEIRO,05/12/2018,NaN,"1590,0000"
6,12018,110746,INTERVENCAO FEDERAL RIO DE JANEIRO,3,Concorrência,00144002919201831,Objeto: Contratação de empresa especializada n...,Evento de Resultado de Julgame,20000,Presidência da República,20101,Presidência da República,DF,BRASILIA,26/12/2018,NaN,"2677075,9700"
7,12018,113207,COMISSAO NACIONAL DE ENERGIA NUCLEAR-CRCN-CO,5,Pregão,012030000068/2018,Objeto: Pregão Eletrônico - Contratação exclus...,Publicado,24000,"Ministério da Ciência, Tecnologia e Inovaç",20301,Comissão Nacional de Energia Nuclear,GO,ABADIA DE GOIAS,06/12/2018,29/11/2018,"124000,0000"
8,12018,120006,GRUPAMENTO DE APOIO DE BRASILIA,2,Tomada de Preços,67284006392201890,Objeto: Contratação de empresa especializada p...,Publicado,52000,Ministério da Defesa,52111,Comando da Aeronáutica,DF,BRASILIA,17/12/2018,NaN,"1692588,0800"
9,12018,120628,GRUPAMENTO DE APOIO DE BELEM,1,Convite,67215014829201882,Objeto: Construção do posto de combustível e l...,Evento de Resultado de Julgame,52000,Ministério da Defesa,52111,Comando da Aeronáutica,PA,BELEM,19/12/2018,NaN,"194247,8900"

In [7]:
df.columns

Index(['Número Licitação', 'Código UG', 'Nome UG', 'Código Modalidade Compra',
       'Modalidade Compra', 'Número Processo', 'Objeto', 'Situação Licitação',
       'Código Órgão Superior', 'Nome Órgão Superior', 'Código Órgão',
       'Nome Órgão', 'UF', 'Município', 'Data Resultado Compra',
       'Data Abertura', 'Valor Licitação'],
      dtype='object')

In [8]:
df[df['Situação Licitação']=='Encerrado']

,Número Licitação,Código UG,Nome UG,Código Modalidade Compra,Modalidade Compra,Número Processo,Objeto,Situação Licitação,Código Órgão Superior,Nome Órgão Superior,Código Órgão,Nome Órgão,UF,Município,Data Resultado Compra,Data Abertura,Valor Licitação
3,12018,925135,BANCO CENTRAL DO BRASIL - RECIFE,6,Dispensa de Licitação,148097,"Objeto: TV LED de 65 polegadas, UHD 4k, com co...",Encerrado,20101,Sem informação,25201,BANCO CENTRAL DO BRASIL-ORC.FISCAL/SEG.SOCIAL,-3,Inválido,04/12/2018,30/11/2018,"11075,9900"
16,12018,130129,SUPERINT.REG.DE DESENV.DA LAV.CACAUEIRA/MT,6,Dispensa de Licitação,0000000000032018,Objeto: Atender despesas com telefonia fixa e ...,Encerrado,22000,Ministério da Agricultura e Pecuária,22000,Ministério da Agricultura e Pecuária - Unid,MT,ALTA FLORESTA,06/12/2018,NaN,"1541,7000"
18,12018,135097,EMBRAPA CAFE,7,Inexigibilidade de Licitação,21163.000694/2018,Objeto: Serviço de genotipagem de 384 amostras...,Encerrado,22000,Ministério da Agricultura e Pecuária,22202,Empresa Brasileira de Pesquisa Agropecuária,DF,BRASILIA,04/12/2018,NaN,"90504,0000"
19,12018,152140,IFB - CAMPUS TAGUATINGA NORTE,6,Dispensa de Licitação,23162004935201845,Objeto: Contratação de empesa especializada a ...,Encerrado,26000,Ministério da Educação,26428,Instituto Federal de Brasília,DF,BRASILIA,31/12/2018,NaN,"2068,0000"
24,12018,153092,BIBLIOTECA CENTRAL DA UFPE,6,Dispensa de Licitação,23076025958201862,Objeto: Aquisição de Equipamento de Proteção I...,Encerrado,26000,Ministério da Educação,26242,Universidade Federal de Pernambuco,PE,RECIFE,06/12/2018,29/11/2018,"5609,0000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15327,907662018,926130,DIVISÃO DE CENTRO DE SERV COMPRATILHADOS BSB,6,Dispensa de Licitação,PL.CSG.A.90766,"Objeto: Fornecimento de fogão, para entrega na...",Encerrado,20101,Sem informação,91081,FURNAS-CENTRAIS ELETRICAS S.A.,-3,Inválido,10/12/2018,04/12/2018,"817,2000"
15328,907732018,926130,DIVISÃO DE CENTRO DE SERV COMPRATILHADOS BSB,6,Dispensa de Licitação,PL.CSG.A.90773,Objeto: Prestação de serviços para locação de ...,Encerrado,20101,Sem informação,91081,FURNAS-CENTRAIS ELETRICAS S.A.,-3,Inválido,20/12/2018,05/12/2018,"8400,0000"
15329,908252018,926130,DIVISÃO DE CENTRO DE SERV COMPRATILHADOS BSB,6,Dispensa de Licitação,PL.CSG.A.90825,Objeto: Coleta e descarte de resíduos industri...,Encerrado,20101,Sem informação,91081,FURNAS-CENTRAIS ELETRICAS S.A.,-3,Inválido,21/12/2018,17/12/2018,"9040,0000"
15333,990922018,158139,"INST.FED.DE EDUC.,CIENC.E TEC.FLUMINENSE",6,Dispensa de Licitação,23317009092201862,Objeto: Aquisição de material para revisão do ...,Encerrado,26000,Ministério da Educação,26434,Instituto Federal Fluminense,RJ,CAMPOS DOS GOYTACAZES,03/12/2018,NaN,"1149,7500"
15334,996252018,153035,UNIVERSIDADE FEDERAL DO TRIANGULO MINEIRO,6,Dispensa de Licitação,23085000625201811,Objeto: Pagamento da taxa referente ao primeir...,Encerrado,26000,Ministério da Educação,26254,Universidade Federal do Triângulo Mineiro,MG,UBERABA,04/12/2018,NaN,"298,0000"

In [9]:
df['Situação Licitação'].value_counts()

Situação Licitação
Encerrado                         9016
Publicado                         3709
Evento de Resultado de Julgame    1922
Retificação                        127
Evento de Alteração Publicad        93
Evento de Suspensão Publicado       72
Anulação                            67
Revogação                           63
Divulgado                           55
Evento de Adiamento Publicado       46
Evento de Retificação Public        45
Evento de Revogação Publicad        40
Evento de Alteração de Resul        37
Evento de Anulação Publicado        18
Evento de Retificação Divulg         7
Inválido                             4
Evento de Habilitação Public         4
Evento de Alteração Divulgad         4
Evento de Reabertura de Prazo        4
Evento de Adiamento Divulgado        3
Name: count, dtype: int64

# Tratando valores faltantes

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15336 entries, 0 to 15335
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Número Licitação          15336 non-null  int64
 1   Código UG                 15336 non-null  int64
 2   Nome UG                   15336 non-null  object
 3   Código Modalidade Compra  15336 non-null  int64
 4   Modalidade Compra         15336 non-null  object
 5   Número Processo           15336 non-null  object
 6   Objeto                    15336 non-null  object
 7   Situação Licitação        15336 non-null  object
 8   Código Órgão Superior     15336 non-null  int64
 9   Nome Órgão Superior       15336 non-null  object
 10  Código Órgão              15336 non-null  int64
 11  Nome Órgão                15336 non-null  object
 12  UF                        15336 non-null  object
 13  Município                 15336 non-null  object
 14  Data Resultado Compra     15336 non-null  object
 15  Data Abertura             4688 non-null   object
 16  Valor Licitação           15336 non-null  object
dtypes: int64(5), object(12)
memory usage: 2.0+ MB

In [11]:
len(df)

15336

In [12]:
df.groupby('Data Abertura', dropna=False)['Número Licitação'].nunique()

Data Abertura
01/06/2018       1
01/10/2018       5
01/11/2018      27
01/12/2018       1
02/04/2018       1
              ...
31/07/2018       1
31/08/2018       1
31/10/2018      27
31/12/2018       9
NaN           1512
Name: Número Licitação, Length: 180, dtype: int64

In [14]:
df.groupby('Data Abertura', dropna=False)['Número Licitação'].nunique()

Data Abertura
01/06/2018       1
01/10/2018       5
01/11/2018      27
01/12/2018       1
02/04/2018       1
              ...
31/07/2018       1
31/08/2018       1
31/10/2018      27
31/12/2018       9
NaN           1512
Name: Número Licitação, Length: 180, dtype: int64

In [15]:
df['Data Abertura'].mode()

0    04/12/2018
Name: Data Abertura, dtype: object

In [16]:
df.loc[df['Data Abertura'].isnull(), 'Data Abertura'] = '00/00/0000'

In [17]:
df['Data Abertura'].isnull().value_counts()

Data Abertura
False    15336
Name: count, dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15336 entries, 0 to 15335
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Número Licitação          15336 non-null  int64
 1   Código UG                 15336 non-null  int64
 2   Nome UG                   15336 non-null  object
 3   Código Modalidade Compra  15336 non-null  int64
 4   Modalidade Compra         15336 non-null  object
 5   Número Processo           15336 non-null  object
 6   Objeto                    15336 non-null  object
 7   Situação Licitação        15336 non-null  object
 8   Código Órgão Superior     15336 non-null  int64
 9   Nome Órgão Superior       15336 non-null  object
 10  Código Órgão              15336 non-null  int64
 11  Nome Órgão                15336 non-null  object
 12  UF                        15336 non-null  object
 13  Município                 15336 non-null  object
 14  Data Resultado Compra     15336 non-null  object
 15  Data Abertura             15336 non-null  object
 16  Valor Licitação           15336 non-null  object
dtypes: int64(5), object(12)
memory usage: 2.0+ MB

In [19]:
df.groupby('Data Abertura', dropna=False)['Número Licitação'].nunique()

Data Abertura
00/00/0000    1512
01/06/2018       1
01/10/2018       5
01/11/2018      27
01/12/2018       1
              ...
31/01/2018       1
31/07/2018       1
31/08/2018       1
31/10/2018      27
31/12/2018       9
Name: Número Licitação, Length: 180, dtype: int64